// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZd_UENUVZQVV4HBU4c_4X59RsRNDqPLM',
    appId: '1:60699627310:web:6dac08ca075f1a204634bf',
    messagingSenderId: '60699627310',
    projectId: 'inventory-management-app-4b1f9',
    authDomain: 'inventory-management-app-4b1f9.firebaseapp.com',
    storageBucket: 'inventory-management-app-4b1f9.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAo1lyCuOW2LdCI7tEy-_L4H8dV0sZ_plc',
    appId: '1:60699627310:android:cf37b320f26cc6574634bf',
    messagingSenderId: '60699627310',
    projectId: 'inventory-management-app-4b1f9',
    storageBucket: 'inventory-management-app-4b1f9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADdff0t7CBR5T1WJTyXfi_AT2SJVCI8v8',
    appId: '1:60699627310:ios:0df3597d60436faf4634bf',
    messagingSenderId: '60699627310',
    projectId: 'inventory-management-app-4b1f9',
    storageBucket: 'inventory-management-app-4b1f9.firebasestorage.app',
    iosBundleId: 'com.example.inventoryManagementApp',
  );
}
